spring:
    jackson:
        default-property-inclusion: non_null
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    profiles:
        active: '@activatedProperties@'
