version: '3'
name: water-tank

services:
  db:
    container_name: water_tank_database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=water_tank
      - POSTGRES_USER=watertankuser
      - POSTGRES_PASSWORD=WaterTankUser123!
    volumes:
      - ./data:/var/lib/postgresql/data

